package vcMorraCinese;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelMorraCinese.Model;
/**
 *
 * @author Vittorio Privitera
 */
public class GameCineseVC extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameCineseVC.class.getName());
    private Model model;
    public GameCineseVC() {
        initComponents();
        this.model=new Model();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label1_lbl = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        puntMax_txt = new javax.swing.JTextField();
        forbici_btn = new javax.swing.JButton();
        carta_btn = new javax.swing.JButton();
        sasso_btn = new javax.swing.JButton();
        sceltaPc_lbl = new javax.swing.JLabel();
        sfida_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        punti_lbl = new javax.swing.JLabel();
        jLabel4_lbl = new javax.swing.JLabel();
        lanci_lbl = new javax.swing.JLabel();
        termina_btn = new javax.swing.JButton();
        iniza_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        puntiPc_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("CARTA FORBICE E SASSO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label1_lbl.setText("NOME:");

        nome_txt.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Punteggio MAX:");

        forbici_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        forbici_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forbici_btnActionPerformed(evt);
            }
        });

        carta_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        carta_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        carta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta_btnActionPerformed(evt);
            }
        });

        sasso_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        sasso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sasso_btnActionPerformed(evt);
            }
        });

        sceltaPc_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start.png"))); // NOI18N

        sfida_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sfida_lbl.setText("? VS ?");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("PUNTI UTENTE:");

        punti_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        punti_lbl.setText("0");

        jLabel4_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4_lbl.setText("Lanci:");

        lanci_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lanci_lbl.setText("0");

        termina_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        termina_btn.setText("TERMINA");
        termina_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        termina_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termina_btnActionPerformed(evt);
            }
        });

        iniza_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iniza_btn.setText("INIZIA");
        iniza_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iniza_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniza_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("PUNTI PC:");

        puntiPc_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        puntiPc_lbl.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puntMax_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(label1_lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(termina_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(iniza_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(carta_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sasso_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(forbici_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(sfida_lbl)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sceltaPc_lbl)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(puntiPc_lbl)
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel4_lbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lanci_lbl)))
                                        .addGap(11, 11, 11))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(punti_lbl)))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1_lbl)
                    .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniza_btn))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(puntMax_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(termina_btn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(forbici_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(sasso_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(sceltaPc_lbl)
                        .addGap(24, 24, 24)
                        .addComponent(sfida_lbl)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(punti_lbl)
                    .addComponent(jLabel4_lbl)
                    .addComponent(lanci_lbl)
                    .addComponent(jLabel4)
                    .addComponent(puntiPc_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniza_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniza_btnActionPerformed
       if(this.model.isInGioco())return;
       String nome;
       int puntiMax;
       try
       {
           nome=nome_txt.getText();
           puntiMax=Integer.parseInt(puntMax_txt.getText().trim());
           this.model.iniziaPartita(nome,puntiMax);
           //puntMax_txt.setText(""+this.model.getPuntiMax());
          // nome_txt.setText(this.model.getNome());
           abilitaDisabilita(true);
           allinaModel();
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,"Hai inserito un elemento non valido nei puntiMax");
       }            
    }//GEN-LAST:event_iniza_btnActionPerformed

    private void forbici_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forbici_btnActionPerformed
        gestioneButton(evt);
    }//GEN-LAST:event_forbici_btnActionPerformed

    private void carta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta_btnActionPerformed
        gestioneButton(evt);
    }//GEN-LAST:event_carta_btnActionPerformed

    private void sasso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sasso_btnActionPerformed
        gestioneButton(evt);
    }//GEN-LAST:event_sasso_btnActionPerformed

    private void termina_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termina_btnActionPerformed
        terminaPartita();
    }//GEN-LAST:event_termina_btnActionPerformed
// fare con un metodo private che gestisce il clcick conteporaneo 
    /*
    private void gestisciBotton(java.awt.event.ActionEvent evt)
    {
        dispaccer grafico
    }*/
    
    private String prendiScelta()
    {
        if(this.model.getSceltaPc()==1) return "Sasso";
        else if(this.model.getSceltaPc()==2) return "Carta";
        else return "Forbice";
    }
    
    private void gestioneButton(java.awt.event.ActionEvent evt)
    {
        JButton b=(JButton)evt.getSource();
        //System.out.println(b.getIcon());
        if(b.getIcon()==forbici_btn.getIcon())gestioneScelta(3,"Forbici");
        else if(b.getIcon()==carta_btn.getIcon())gestioneScelta(2,"Carta");
        else gestioneScelta(1,"Sasso");
    }
    
    private void gestioneScelta(int num,String sc)
    {
        int esito=this.model.gioco(num);
        try 
        {
            Thread.sleep(1000);
            sceltaPc_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/"+this.model.getSceltaPc()+".png")));
        }
        catch(Exception e) 
        {
        }
        switch(esito)
        {
            case -9: // non siamo in gioco;
                JOptionPane.showMessageDialog(null,"Non stai giocando");
                terminaPartita();
                break;
            case -8:
                JOptionPane.showMessageDialog(null,"Ha vinto "+this.model.getNome());
                terminaPartita();
                break;
            case -7:
                JOptionPane.showMessageDialog(null,"Ha vinto il pc");
                terminaPartita();
                break;
            default:
                punti_lbl.setText(""+this.model.getPuntiUtente());
                lanci_lbl.setText(""+this.model.getLanci());
                sfida_lbl.setText(sc+" VS "+prendiScelta());
                puntiPc_lbl.setText(""+this.model.getPuntiPc());
                //System.out.println(this.model.getPuntiPc());
        } 
    }
    private void terminaPartita()
    {
        this.model.terminaPartita();
        abilitaDisabilita(false);
    }   
    private void abilitaDisabilita(boolean b) // false che non siamo in gioco
    {
        nome_txt.setEditable(!b);
        puntMax_txt.setEditable(!b);
        carta_btn.setEnabled(b);
        sasso_btn.setEnabled(b);
        forbici_btn.setEnabled(b);
        iniza_btn.setEnabled(!b);
        termina_btn.setEnabled(b);
    }
    private void allinaModel()
    {
        punti_lbl.setText("0");
        lanci_lbl.setText("0");
        sfida_lbl.setText("? VS ?");
        puntiPc_lbl.setText("0");
        sceltaPc_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameCineseVC().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carta_btn;
    private javax.swing.JButton forbici_btn;
    private javax.swing.JButton iniza_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1_lbl;
    private javax.swing.JLabel lanci_lbl;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JTextField puntMax_txt;
    private javax.swing.JLabel puntiPc_lbl;
    private javax.swing.JLabel punti_lbl;
    private javax.swing.JButton sasso_btn;
    private javax.swing.JLabel sceltaPc_lbl;
    private javax.swing.JLabel sfida_lbl;
    private javax.swing.JButton termina_btn;
    // End of variables declaration//GEN-END:variables
}
